name: flutter_jira_issue_collector_example
description: Example app for flutter_jira_issue_collector package.
publish_to: 'none'

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_jira_issue_collector:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
